# Server
server.port=8082

# Neon.tech Database
spring.datasource.url=jdbc:postgresql://ep-odd-waterfall-a1juougx-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_aECFtImR7h0N
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Inter-service URL
department.service.url=http://localhost:8080/departments